name: Deploy to Deepin OS

on:
  push:
    branches:
      - main  # Change to your main branch name in Bitbucket

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from Bitbucket
        uses: actions/checkout@v2
        with:
          repository: 'ccjktest/project-new'
          ref: 'main'
          token: ${{ secrets.BITBUCKET_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Deploy to Deepin OS
        run: |
          # Set up SSH agent and add private key
          eval $(ssh-agent -s)
          ssh-add <(echo "$PRIVATE_KEY")

          # Copy code to Deepin OS using SCP
          scp -r /home/runner/work/project-new/project-new/* umer@MuhammadAsim:/home/umer/Desktop/octi
